---
name: Action

"on":
  push:
    branches:
      - main
    paths:
      - ".github/workflows/*.yml"
  pull_request:
    branches:
      - "*"
    paths:
      - ".github/workflows/*.yml"
  workflow_dispatch: {}
  merge_group:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  lint:
    name: Action lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: actionlint
        uses: reviewdog/action-actionlint@db58217885f9a6570da9c71be4e40ec33fe44a1f # v1.65.0
        env:
          SHELLCHECK_OPTS: -o all
