---
name: Lint

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}
  merge_group:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  md-lint:
    name: Markdown Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: .tool-versions
          cache: "npm"
          cache-dependency-path: "package-lock.json"
      - run: npm ci
      - run: make check-md

  yaml-lint:
    name: YAML Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - run: make check-yaml

  action-lint:
    name: Action Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install actionlint
        run: |
          version=1.7.11
          url=https://github.com/rhysd/actionlint/releases/download
          curl -sSL "${url}/v${version}/actionlint_${version}_linux_amd64.tar.gz" \
            | sudo tar xzf - -C /usr/local/bin actionlint
      - run: make check-actions
