---
name: Lint

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}
  merge_group:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  md-lint:
    name: Markdown Lint

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      # uses .markdownlint.yml for configuration
      - name: markdownlint
        uses: DavidAnson/markdownlint-cli2-action@992badcdf24e3b8eb7e87ff9287fe931bcb00c6e # v20.0.0
        with:
          globs: |
            .github/**/*.md
            *.md

  yaml-lint:
    name: YAML Lint

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: yamllint
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3.1.1
        with:
          file_or_dir: |
            .github/**/*.yml
            .*.yml
          strict: true
          config_file: .yamllint.yml

  action-lint:
    name: Action Lint

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: actionlint
        uses: reviewdog/action-actionlint@50b75b9513baa71e6a1899a1ebaa9ac9851cf16c # v1.66.0
        env:
          SHELLCHECK_OPTS: -o all
